.ORIG X1500
;SAVE DEM REGISTERS
ST R0, SAVE_R0
ST R1, SAVE_R1
ST R2, SAVE_R2
ST R3, SAVE_R3
ST R4, SAVE_R4
;GET STUFF FROM KBDR
LDI R0, KBDR		;GET INPUT CHAR FROM KBDR
;CHECK IF INPUT CHAR IS CAPITAL
ADD R1, R0, #0		;COPY INPUT CHAR TO R1
LD R2, CAPCHECK		;INVERSE VALUE OF 'a'
ADD R1, R1, R2		;COMPARE INPUT TO 'a'
;NOOO? RTI YO
BRzp GET_OUT		;IF NEG, THEN CAPITAL
;YESSS? 
;BUT IS IT A LETTER?
LD R2, A		;NEGHEX OF A
ADD R1, R0, #0		;INPUT COPIED TO R1
ADD R1, R1, R2		;COMPARE BEGIN OF CAPS TO INPUT
BRN GET_OUT
LD R2, Z		;NEGHEX OF Z
ADD R1, R0, #0		;INPUT IN R1
ADD R1, R1, R2		;COMPARE END OF CAPS TO INPUT
BRP GET_OUT
;STARTING ON NEW LINE 
;PRINT THE CAPITAL VERSION 10X THEN THE LOWERCASE 10X
ADD R1, R0, #0		;INPUT INTO R1
AND R2, R2, #0
LD R2, CAPTOLOW
ADD R0, R1, R2		;lowercase VERSION
			;OF INPUT
;CHECK IF DSR IS READY FO' ACTION


READY	LDI R4, DSR	;GET DSR OVER HERE
	BRZP READY	;NOT READY? POLL DAT YO
;DSR IS READY! STORE INPUT CHAR TO DDR (XFE06)
LD R4, NUM10		;SET R4 AS COUNTER FO' CAP OUTPUT

AND R2, R2, #0		;CLEAR
ADD R2, R2, X0A		;LINE FILL IN R2
STI R2, DDR		;PRINT OUT A LF YO
CAPOUT	STI R1, DDR
	ADD R4, R4, #-1
	BRZP CAPOUT
LD R4, NUM10


LOWOUT	STI R0, DDR
	ADD R4, R4, #-1
	BRZP LOWOUT
;PRINT A LINE FEED BROSKI
;LD R0, X0A
STI R2, DDR
;GET BACK ALL DEM REGISTERS
LD R0, SAVE_R0
LD R1, SAVE_R1
LD R2, SAVE_R2
LD R3, SAVE_R3
LD R4, SAVE_R4
;TIME TO RTI
GET_OUT RTI
SAVE_R0 .BLKW 1
SAVE_R1 .BLKW 1
SAVE_R2 .BLKW 1
SAVE_R3 .BLKW 1
SAVE_R4 .BLKW 1
DDR .FILL XFE06
DSR .FILL XFE04
CAPTOLOW .FILL X20
CAPCHECK .FILL X-61
NUM10 .FILL #10
KBDR .FILL XFE02
A .FILL X-41
Z .FILL X-5A
.END