.ORIG X3000
;INITIALIZE STACK POINTER
LD R6, STACK			;SP AT X3000, EMPTY
;KB IVT ENTRY SETUP
LD R5, ENTRY_START		;MEM LOC X1500
LD R4, KBIV
STR R5, R4, #0			;MEM LOC OF INTERRUPT SERVICE START IN KB VECTOR IN IVT
;ENABLE KB INTERRUPTS
CHECK	LD R2, BITM15		;X4000
	LD R3, KBSR		;MEM LOC OF KBSR
	STR R2, R3, #0		;X4000 IN KBSR
	;LEA R3, KBDR		;R3 HAS KBDR YO
	;STR R5, R3, #0		;KBSR SET IE BIT
;START PROGRAM WITH TEXAS CHECKERBOARD
FIRST	LEA R0, FIRSTLINE	;READY TO PRINT OUT FIRST LINE OF TEXASESES
	PUTS			;ACTUALLY PRINTS OUT FIRSTLINE
	LD R0, LF		;LINE FILL YO
	OUT			;PRINT DAT LINE FILL
JSR DELAY
SECOND 	LEA R0, SECONDLINE	;READY TO PRINT OUT SECOND LINE OF TEXASESESESESESESESESES
	PUTS			;ACTUALLY PRINTS OUT SECONDLINE
	LD R0, LF		;GOOD OL' LINE FILL
	OUT			;I MISSED YOU LINE FILL, WHERE YA BEEN
JSR DELAY
BRNZP FIRST
HALT

DELAY	ST R1, SAVER1
	LD R1, COUNT
REP	ADD R1, R1, #-1
	BRP REP
	LD R1, SAVER1
RET

ENTRY_START .FILL X1500
KBIV .FILL X0180
KBSR .FILL XFE00
KBDR .FILL XFE02
DSR .FILL XFE04
DDR .FILL XFE06
COUNT .FILL x2500
SAVER1 .BLKW 1
STACK .FILL X3000
LF .FILL X0A
FIRSTLINE .STRINGZ "Texas       Texas       Texas       Texas"
SECONDLINE .STRINGZ "       Texas       Texas       Texas"
BITM15 .FILL X4000
BITM16 .FILL X8000
.END